### ISSUE TITLE
[FEATURE]: Delete server cache

### ISSUE THREAD

**Issue by nwvh** [tabarra/txAdmin#950]
### Scope

Web, Developer API

### Feature Description

Option to delete the server cache (`cache/` folder) with a button in the web panel, or even better, option to set automatic cache deletion on server restart.

### Use Case

It's good to clear your server cache from time to time, as it may help with streaming, or performance related issues. If this feature is going to become a part of txAdmin, a lot of (not only) server owners may find it useful.

### Proposed Solution

* CTA in the web panel
* On (automatic) server restart, delete the `cache/` folder

### Additional Info

![image (2)](https://github.com/tabarra/txAdmin/assets/76164598/d9c89cc2-8b04-4aab-bcf4-3202ce4d4e28)
![image (3)](https://github.com/tabarra/txAdmin/assets/76164598/3c3da215-5bd1-469e-9f2d-58151bd8cdf8)

**Comment by tabarra** [comment]
Hey there, thanks for the suggestion.  
I'm not completely against a button to delete the cache on the master actions page, but I do think txAdmin is not the right place for that due to:  
- I/O thread blocking;
- It will validate the idea that deleting the cache is very useful, when it just isn't.
- Danger of misconfiguration ending with it wiping the entire server or other important files.  

And regarding the automatic cache wipes, this is an absolute no.  
The entire reason a cache exists it to cache data, if you keep wiping the cache you are needlessly wasting time re-caching everything at server boot.  
Please check: #193, #95 and [the docs on cache wiping](https://github.com/tabarra/txAdmin/blob/master/docs/cache_wiping.md).  
  
Thank you
